language: android

android:
  components:
    - tools
    - platform-tools
    - tools
    - sys-img-armeabi-v7a-google_apis-25
    - android-26
    - build-tools-25.0.2

before_install:
- yes | sdkmanager "platforms;android-26"



notifications:
  email:
    recipients:
      - antoniofarina1702@gmail.com
      - luigimartire94@gmail.com
    on_success: always
    on_failure: never

before_script:
  - android list targets
  - echo no | android create avd -n test -t android-25 -b google_apis/armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
