language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

notifications:
  email:
    recipients:
      - antoniofarina1702@gmail.com
      - luigimartire94@gmail.com
    on_success: always
    on_failure: always

