language: android
android:
  components:
    - build-tools-26.0.2
    
notifications:
  email:
    recipients:
      - antoniofarina1702@gmail.com
      - luigimartire94@gmail.com
    on_success: always
    on_failure: always

