language: android

before_install:
- yes | sdkmanager "platforms;android-26"


notifications:
  email:
    recipients:
      - antoniofarina1702@gmail.com
      - luigimartire94@gmail.com
    on_success: always
    on_failure: always

